---
services:
  br777_renderfarm_api:
    container_name: br777_renderfarm_api
    restart: always
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.renderapi.rule=Host(`render.botfarm.live`)"
      - "traefik.http.routers.renderapi.entrypoints=websecure"
      - "traefik.http.routers.renderapi.tls.certresolver=myresolver"
      - "traefik.http.routers.renderapi-http.rule=Host(`render.botfarm.live`)"
      - "traefik.http.routers.renderapi-http.entrypoints=web"
      - "traefik.http.routers.renderapi-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.renderapi.loadbalancer.server.port=8000"
    networks:
      - frontend

  br777_renderfarm_render:
    restart: always
    build:
      context: ./
      dockerfile: ./render/Dockerfile
    deploy:
      replicas: 4
      mode: replicated
      resources:
        limits:
          cpus: '3.5'
    networks:
      - frontend

  br777_renderfarm_feedscollector:
    container_name: br777_renderfarm_feedscollector
    restart: always
    build:
      context: ./
      dockerfile: ./feedscollector/Dockerfile
    expose:
      - "8000"
    ports:
      - "8000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.renderfeedscollector.rule=Host(`feeds-collector.botfarm.live`)"
      - "traefik.http.routers.renderfeedscollector.entrypoints=websecure"
      - "traefik.http.routers.renderfeedscollector.tls.certresolver=myresolver"
      - "traefik.http.routers.renderfeedscollector-http.rule=Host(`feeds-collector.botfarm.live`)"
      - "traefik.http.routers.renderfeedscollector-http.entrypoints=web"
      - "traefik.http.routers.renderfeedscollector-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.renderfeedscollector.loadbalancer.server.port=8000"
    networks:
      - frontend

networks:
  frontend:
    external: true
