---
services:
  br777_renderfarm_api:
    container_name: br777_renderfarm_api
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    expose:
      - "8000"
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - npm_frontend

  br777_renderfarm_render:
    container_name: br777_renderfarm_render
    build:
      context: ./
      dockerfile: ./render/Dockerfile
    deploy:
      resources:
        limits:
          cpus: '1'
    volumes:
      - ./media:/media
    networks:
      - npm_frontend

networks:
  npm_frontend:
    external: true
